version: '3.4'

services:
   para:
     image: docker push 787952688011.dkr.ecr.us-east-1.amazonaws.com/para:latest
     ports:
       - "8080:8080"
     volumes:
       - type: volume
         source: paraData
         target: /para/data
       - type: volume
         source: paraLib
         target: /para/lib
       - type: bind
         source: ./para-application.conf
         target: /para/application.conf
     restart: always
     environment:
       - JAVA_OPTS=-Dconfig.file=/para/application.conf -Dloader.path=/para/lib

   scoold:
     depends_on:
       - para
     image: erudikaltd/scoold:latest_stable
     ports:
       - "8000:8000"
     volumes:
       - type: bind
         source: ./scoold-application.conf
         target: /scoold/application.conf
     restart: always
     environment:
       - JAVA_OPTS=-Dconfig.file=/scoold/application.conf
       - BOOT_SLEEP=5
volumes:
  paraData:
  paraLib:
